image: php:8.1

pipelines:
  default:
    - step:
        name: Run tests
        caches:
          - composer
        script:
          # Update the package repository and install necessary tools
          - apt-get update
          - apt-get install -y unzip libzip-dev git

          # Install Xdebug
          # - pecl install xdebug
          # - docker-php-ext-enable xdebug

          # Install zip extension
          - docker-php-ext-install zip

          # Install Composer
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

          # Install project dependencies
          - composer install

          # Perform checks
          - composer run check

          # Run tests
          - composer run test
